### PR TITLE
Update srh jamaica pipeline

### LINKED ISSUE #5: Pipeline doesn't complete successfully after changes to rpft
The pipeline in this repo was last updated in August and no longer works because it has not kept up with changes to supporting tools such as RapidPro Flow Toolkit and others. The most recent version of the pipeline is contained in:

https://github.com/IDEMSInternational/srh-jamaica-chatbot/blob/main/srh_jamaica_create.ps1

### PR DESCRIPTION
**Pull request by edmoss345**
Update to SRH pipeline to ensure it can run end to end off github actions

### CODE REVIEW

**Comment by edmoss345** [comment]
@istride @fagiothree think I am most of the way there, just a few things that probably still need to be tweaked.

I have just updated the sry_jamaica.py file, so to run the pipeline just use the existing instructions in the readme. The way I have it setup is that the final files go into the output directory. You can choose to either store the intermediary files or not, this option is set in the 'sources' list by setting the 'outputlog' parameter as true or false. Because I am using some temp directories I ran into a problem that some files were being left open as part of the ab_testing step, I therefore had to make a slight tweak to that repo to get everything working correctly. 

https://github.com/IDEMSInternational/rapidpro_abtesting/pull/5

So when testing you either need to merge the above PR or install that branch locally.

@fagiothree when you look at the list of sources you will see that the first one is disabled, I think there is a missing sheet in that particular workbook although cant be sure. The others run ok. I should also point out that for the 'safeguarding_redirect' I am using the v2 code, I was running into errors when some of the flow combinations did not contain a redirect flow name. I think everything is working as expected but it would be good if you could check if the output is as expected.

@istride for the actual functions everything is running in a very similar way to parenttext_v2. Therefore I think to get the github actions working we just need to set the same credentials variable in this repo that you have done with the other parenttext deployments.

**Comment by istride** [comment]
The CREDENTIALS env var was set at the end of June and it should still be usable.

I'm not sure what the difficulty is with ab testing. It does seem odd that we should need to explicitly close log files as I would expect that to be done automatically by the logging framework, so maybe we are doing something we shouldn't be doing. If the pipelines for the other deployments work with the ab testing changes, then please merge them.

It looks like there are functions from the general pipeline being duplicated here. Why not make the general pipeline a dependency and reuse the existing functions? The general pipeline will also bring in the toolkit and ab_testing packages, so we won't have to declare them separately here.

In any case, if @fagiothree is happy then we should merge this and address the outstanding issues later.

**Comment by fagiothree** [comment]
Yes, it is working fine for me. I also pushed some small changes

**Comment by edmoss345** [comment]
@istride , the credentials file in this repo is not the same as the other parenttext deployments. It is from a time when I uploaded a 'credetials' and 'token' file to the repo secrets and it was running in a a similar way to how it runs locally. I think any existing credentials need to be cleared out and then the 'credentials' file to be copied from a working parenttext repo like SA.

I am also not sure exactly what is going on with ab_testing, I just know that in the other pipeline we don't try and remove any of the intermediary files after the run so we don't run into this problem where a file is still open. I have run the parenttext pipeline with the updated code and it still works ok so think this is safe to merge for now, although I don't have the permissions on the ab_testing repo so could you do that merge.

Agreed there is some duplication in functions from parenttext pipeline, but some of the functions I have copied and tweaked slightly just to get something working now. I think we maybe merge this for now if it is working, then come back to this when we work to generalise the pipeline and it's various steps

**Comment by istride** [comment]
I think the credentials are fine, but at least one of the source spreadsheets has restricted access i.e. not publicly readable. If the spreadsheets can't all be made publicly readable, then we need to give read access to the service account for this pipeline.

**Comment by fagiothree** [comment]
Sorry, I had not realised one spreadsheet had restricted access (it had been replaced at some point). I made them all publicly readable for now, but I will need to confirm with NFPB that this is ok with them

**Comment by edmoss345** [comment]
Hmm, still getting an error when trying to run the github actions, not sure what is going on

**Comment by istride** [comment]
One of the sheets was still not publicly readable; I've changed that. There is now a different error.

**Comment by edmoss345** [comment]
Think the problem was some old paths written using windows lexicon, have updated and now the github actions appears to be working. Artifact is the output files.

image

@fagiothree could you confirm you are happy with this if so we can probably merge this into main

**Comment by fagiothree** [comment]
yes, looks good to me, thanks

**Pull request merged**
